# Generated by Django 3.1.7 on 2021-03-04 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=255, verbose_name='Название компании')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('about_company', models.TextField(verbose_name='Краткое описание')),
                ('create_date', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('date_of_change', models.DateField(auto_now_add=True, verbose_name='Дата изменения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Информация о клиентах',
            },
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photo/', verbose_name='Фото')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Пользователь сайта',
                'verbose_name_plural': 'Пользователи сайта',
            },
        ),
        migrations.CreateModel(
            name='ProjectForCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('about_project', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Срок начала')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Срок окончания')),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.companyinformation', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты для компаний',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_channel', models.CharField(choices=[('application', 'Заявка'), ('mail', 'Письмо'), ('site', 'Сайт'), ('initiative', 'Инициатива компании')], max_length=30, verbose_name='Канал общения')),
                ('about', models.TextField(verbose_name='Описание')),
                ('rating', models.IntegerField(default=0, verbose_name='Оценка')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.companyinformation', verbose_name='Компания')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.projectforcompany', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
            },
        ),
    ]
